/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/chess_board.glb -o src/components/ChessBoardModel.tsx 
Author: 3DVISIONROSCA (https://sketchfab.com/3DVisonRosca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-board-abd411ce96d0420f80ae4faf05292207
Title: Chess Board
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
  }
  materials: {
    ['BlackPawn.002']: THREE.MeshStandardMaterial
    BlackSquare: THREE.MeshStandardMaterial
    PerfectColor: THREE.MeshStandardMaterial
    WhiteSquare: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chess_board.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['BlackPawn.002']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.BlackSquare} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.PerfectColor} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.WhiteSquare} />
      </group>
    </group>
  )
}

useGLTF.preload('/chess_board.glb')
